apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: model-platform
data:
  MLFLOW_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:9000"
  MP_HOST_NAME: "model-platform.com"
  MP_REGISTRY_PATH: "registry"
