### OPTIM
POST http://model-platform.com/deploy/data-days-lille/data-days-lille-huggingface-model-1-deployment/predict
Content-Type: application/json

{
  "inputs": {
    "text": "I love this movie!"
  }
}
