###
POST http://0.0.0.0:8001/users/add?email=bob&password=pass!&role=simple_user



###
GET http://0.0.0.0:8001/auth/me
Authorization: {{Authorization}}
### admin
POST http://0.0.0.0:8001/auth/token
Content-Type: application/x-www-form-urlencoded

username=alice@example.com&password=pass!


### maintainer
POST http://0.0.0.0:8001/auth/token
Content-Type: application/x-www-form-urlencoded

username=bob&password=pass!

###
POST http://0.0.0.0:8001/projects/test/add_user?email=bob&role=maintainer
Authorization: {{Authorization}}

###
###
POST http://0.0.0.0:8001/projects/test/change_user_role?email=bob&role=DEVELOPPER
Authorization: {{Authorization}}
