POST http://0.0.0.0:8000/predict
Content-Type: application/json

{
  "inputs": {
    "Pclass": 3,
    "Sex": "male",
    "Age": 22.0,
    "SibSp": 1,
    "Parch": 0,
    "Fare": 7.25,
    "Embarked": "S"
  }
}
