GET http://0.0.0.0:8001/Project 11/models/list

###
GET http://0.0.0.0:8001/test/models/mlflow_explo_titanic/versions

###
GET http://0.0.0.0:8001/test/models/deploy/mlflow_explo_titanic/4

###
GET http://0.0.0.0:8001/test/models/task-status/032e8bfe-6829-4b17-9bb9-3d045729fdf7
