GET http://0.0.0.0:8001/projects/list

###
GET http://0.0.0.0:8001/projects/test/info


###
GET http://0.0.0.0:8001/projects/test/remove


###
POST http://0.0.0.0:8001/projects/add
Content-Type: application/json

{
  "name": "test",
  "owner": "Owner Name",
  "scope": "Project Scope",
  "data_perimeter": "Data Perimeter",
  "connection_parameters": "Connection Parameters"
}

###
GET http://0.0.0.0:8001/projects/test/governance

###
GET http://0.0.0.0:8001/test/deployed_models/list
