channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.2
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - jaraco-collections==5.1.0
  - jinja2==3.1.6
  - numpy==2.2.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - torch==2.6.0
  - transformers==4.50.0
name: mlflow-env
